apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vane-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: vane-redirect-to-https@kubernetescrd
spec:
  rules:
    - host: vane.dropitx.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vane
                port:
                  number: 3000
