apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:s9PWJ4PJFtsRTo6WiYvEEoT4Eq01rNx2mae+yhS7BOfRdTJxsN2Krd9jmzK/6pxNWnRUml/oJTN/Q03Z/2hfSmKWAfYuQqjVyDJgverDoE3pN+nKDcKhCXx4dgYK9gcFULeTSvj7TELDIACrkqysF4EWPLd6oFNq/y9S57oWaXw2G3XPwV2H127yHw+1GPHabIfqjgtrhzdqDD+0ZCeT1mZj7XTdmRdYtxZVjwg6Sg5k91m7fkwWSNm+jZGh7SyRPxwnpnMKjjfz5y0J3E/j1mCYqWXEJ4KaMrPtA394FUdyzMR7HEwHceB8AMm+TMkq,iv:G2rw2+htydgOqDLypUJFKn7SY+fMbTEwLte7cdkDOaM=,tag:EfJu2JbDOVbXMUo0UIee6Q==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: vane
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQUhmRDh1dUJ1aytBdlRQ
            MDhOU2JDUjdtb21YVWh2MHNOalB0NHIyaENBCmFXbGJ3WVgzNW9BaW90cjZzeXFX
            OEZZUzBvaCtJZys0U1QxRzZoanA2eTQKLS0tIDFZRkZsOEdqSXpWRC9VeWxTTGZ4
            L2I1K2YveXZPeEhrWWE1OXFpaGtaTUEKm2chkJGcAf7xFcXge4aG4btPHyEy+T52
            E0TztWq8SK/jDAKSpVf34Z+DoqwQXr3IJ+fVI9xvElIaM7Go9p1bjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ljhl78t9vy4rlcjhxu8hnaf9nqj7yr7x0wf5emqm944jrum00qrqxuh2wv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T09:28:26Z"
    mac: ENC[AES256_GCM,data:Auz8LThLmn5JNUnyV2Hr+KFqLFzuLa7RCFVc/J4IZRjv/Vv9sbdL6UFfY71HwfPpEdLmHdYMxd8XdYxyoiMgmufCBkwykHomMmQu4B1e5SDzwUDo5XGPdDnCom/CI6lIBKs2FqUubGbsGye/En0jpdyL6H3LcSbMATKXJkjRK+o=,iv:hJQ1SHtqrqjtERSltIltI1pOeOvqOXLsjVuV8ppGfWE=,tag:yj4/K15M6iWhozKDa41QSw==,type:str]
    version: 3.13.3
